import getConfig from 'next/config';

const { publicRuntimeConfig } = getConfig();
const {
  BASE_URL,
  ACCOUNT_BASE_URL,
  STORE_API_BASE_URL,
  SELECT_BASE_URL,
  LIBRARY_API_BASE_URL,
  PLATFORM_API_BASE_URL,
  STATIC_URL,
  LOGOUT_URL,
  REVIEW_URL,
  READING_NOTE_URL,
  RIDI_TOKEN_AUTHORIZE_URL,
  RIDI_OAUTH2_CLIENT_ID,
  SENTRY_DSN,
} = publicRuntimeConfig;

const config = {
  BASE_URL,
  ACCOUNT_BASE_URL,
  STORE_API_BASE_URL,
  SELECT_BASE_URL,
  LIBRARY_API_BASE_URL,
  PLATFORM_API_BASE_URL,
  STATIC_URL,
  LOGOUT_URL,
  REVIEW_URL,
  READING_NOTE_URL,
  RIDI_TOKEN_AUTHORIZE_URL,
  RIDI_OAUTH2_CLIENT_ID,
  SENTRY_DSN,
};

export default config;
